apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: rubyserver
  newName: patrickmagalnsx/gitops
  newTag: af96f337571b69b34e37d49b7b01ad7e554f279f
